### ISSUE TITLE
Notebook 00 - Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by ipa-tys** [aws-samples/amazon-sagemaker-from-idea-to-production#10]
Running the 00-start-here notebook from my pre-existing SageMaker domain (IAM permissions added to the execution role).
I had to install Sagemaker 2.219.0 since pip install gave errors otherwise.

I enabled docker access for the SageMaker domain via option 2 (aws sagemaker CLI in terminal) and the check if docker access is ENABLED succeeds.

However, in the bash script under the heading "Install Docker", the last command (docker version -- to validate the Docker Client is able to access Docker Server at [unix:///docker/proxy.sock]) fails:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

There seems to be a mismatch in the Unix socket - is this the reason of the error message?

**Comment by pdifranc** [comment]
If you enabled Docker at the domain level and you had a running jupyterlab app running, you have to stop the space and restart for the settings to be propagated to an existing space

**Comment by ipa-tys** [comment]
Thank you, after stopping and restarting of the space it works now!
