### ISSUE TITLE
Lab 3 fails on statement that creates the pipeline

### ISSUE THREAD

**Issue by unnelt** [aws-samples/amazon-sagemaker-from-idea-to-production#6]
Hi there

The pipeline fails to create in Lab 3 when running pipeline.upsert(role_arn=sm_role). Pipeline.create(role_arn=sm_role) also fails. This error is encountered when doing the workshop both in execution and assignment 
![Image 05-07-2023 at 21 01](https://github.com/aws-samples/amazon-sagemaker-from-idea-to-production/assets/77478958/c70b18b1-f99a-497b-8eb2-59e90fb39a5a)

**Comment by ConstantSun** [comment]
Maybe due to the wrong sagemaker sdk version, run the cell from lab 0:
```
pip install sagemaker==2.132.0
``` 
<img width="1050" alt="image" src="https://github.com/aws-samples/amazon-sagemaker-from-idea-to-production/assets/26327367/bd950773-37e4-496f-89da-b33ef8e4e035">
